### ISSUE TITLE
Failures when running tests locally (`Style/EndlessMethod` related?)

### ISSUE THREAD

**Issue by andyw8** [standardrb/standard#489]
:wave: I'm seeing 2 strange test failures (likely related) when running the tests locally. I'll try track down the cause, but thought I'd log it here in case anyone else encounters it.

It seems the auto-correct is running for `Style/EndlessMethod` even though it's disabled in `config/base.yml`.

It's possibly something on my local machine is clashing with the config, but I've checked the locations listed on https://docs.rubocop.org/rubocop/1.39/configuration.html#config-file-locations and nothing is present.

```
standard main % ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
standard main % bundle exec rake test
Run options: --seed 55383

# Running:

...................................F..F.....................................

Finished in 8.823195s, 8.6137 runs/s, 14.8472 assertions/s.

  1) Failure:
Standard::Runners::RubocopTest#test_print_corrected_output_on_stdin_with_corrections_on_stderr [/Users/andy/src/github.com/andyw8/testdouble/standard/test/standard/runners/rubocop_test.rb:84]:
--- expected
+++ actual
@@ -1,6 +1,4 @@
 "# frozen_string_literal: true
 " + "
-" + "def Foo
-" + "  'hi'
-" + "end
+" + "def Foo = 'hi'
 "


  2) Failure:
Standard::Runners::RubocopTest#test_print_corrected_output_on_stdin [/Users/andy/src/github.com/andyw8/testdouble/standard/test/standard/runners/rubocop_test.rb:71]:
--- expected
+++ actual
@@ -8,15 +8,17 @@
 " +
 "C:  2:  1: [Corrected] Layout/EmptyLineAfterMagicComment: Add an empty line after magic comments.
 " +
-"C:  2:  8: [Corrected] Style/Semicolon: Do not use semicolons to terminate expressions.
+"C:  2:  1: [Corrected] Style/SingleLineMethods: Avoid single-line method definitions.
 " +
-"C:  2:  9: [Corrected] Layout/TrailingWhitespace: Trailing whitespace detected.
+"C:  3:  1: [Corrected] Style/SingleLineMethods: Avoid single-line method definitions.
 " +
 "C:  3:  5: Naming/MethodName: Use snake_case for method names.
 " +
+"C:  3:  8: [Corrected] Style/DefWithParentheses: Omit the parentheses in defs when the method doesn't accept any arguments.
+" +
 "
 " +
-"1 file inspected, 7 offenses detected, 6 offenses corrected
+"1 file inspected, 8 offenses detected, 7 offenses corrected
 " +
 "====================
 " +
@@ -24,9 +26,5 @@
 " +
 "
 " +
-"def Foo
-" +
-"  'hi'
-" +
-"end
+"def Foo = 'hi'
 "


76 runs, 131 assertions, 2 failures, 0 errors, 0 skips
Coverage report generated for Unit Tests to /Users/andy/src/github.com/andyw8/testdouble/standard/coverage. 950 / 995 LOC (95.48%) covered.
rake aborted!
Command failed with status (1)
/Users/andy/.asdf/installs/ruby/3.1.2/bin/bundle:25:in `load'
/Users/andy/.asdf/installs/ruby/3.1.2/bin/bundle:25:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by andyw8** [comment]
btw I'm using the asdf version manager, in case that might be a factor. In particular, I know that it doesn't set the `RUBY_VERSION` env variable: https://github.com/asdf-vm/asdf-ruby/issues/293

**Comment by andyw8** [comment]
Update: I'm seeing the same failure on a different machine using `chruby`, so it seems `asdf` isn't the issue.

**Comment by andyw8** [comment]
Also, it seems to be independent of the Ruby version. I'm seeing the same failure in 2.7.

**Comment by andyw8** [comment]
In case it helps, here's the `standardrb -h` output:

```
Having trouble? Here's some diagnostic information:

        Ruby version: 3.1.3
   Current directory: /Users/andyw8/src/github.com/testdouble/standard
     RuboCop version: 1.39.0
    Standard version: 1.19.0
Standard config file: /Users/andyw8/src/github.com/testdouble/standard/.standard.yml
```

**Comment by searls** [comment]
Hey Andy! Try as I might, I just can't get the build to fail, locally or [in CI](https://github.com/testdouble/standard/actions/runs/3620509968)

I tried 3.1.2 and then did a fresh install of 3.1.3 and couldn't get the tests to fail. I just updated all the dev deps, the version of bundle used to generate the lockfile, and loosened our new LSP dep and cut a new release, 1.19.1, as well.

Only thing I can imagine based on your comment is that you have a `STANDARDOPTS` environment variable goofing things up maybe? It's the only global-ish way I can think of to alter its behavior (but then, only when run under rake…)

What OS are you on? What's your Bundler version?

**Comment by andyw8** [comment]
Thanks Justin, I tried v1.19.1 issue but same problem. I'm highly suspect it's something in do with my configuration so I'll try dig in some more.

```
standard main % bundle -v
Bundler version 2.3.22
standard main % echo $STANDARDOPTS

standard main % sw_vers
ProductName:		macOS
ProductVersion:		13.0.1
BuildVersion:		22A400
```

**Comment by andyw8** [comment]
Small update: If I move the repo out of my home directory, e.g. into `/tmp`, then it passes 🤔

**Comment by searls** [comment]
Any `.ruby-version`, `.tool-versions`, similar dotfiles in the previous path hierarchy? Struggling to imagine why else path would impact it

**Comment by saturnflyer** [comment]
I've seen the same issues locally. I'll try to update with anything I find

**Comment by maxjacobson** [comment]
I was also seeing this test failure and was glad to see that I wasn't alone.

I think I've gotten to the bottom of it, at least for myself...

I had run `rbenv local 3.2.2`, which created a `.ruby-version` file that said `3.2.2` inside of the repository to signal to rbenv that it should auto-switch to a new version of ruby in this directory. With that file present, the test failure occurs. If I delete the file, and instead run `rbenv global 3.2.2` to use 3.2.2 everywhere, then the test passes.

Here's what seems to be happening:

1. This test invokes rubocop with a very minimalist config that doesn't specify the target ruby version
2. rubocop tries to determine a target ruby version based on a [variety of sources](https://github.com/rubocop/rubocop/blob/v1.50.2/lib/rubocop/target_ruby.rb#L237-L244) and will actually notice and respect that `.ruby-version` file
3. now that it knows it's targeting ruby 3.2.2, the behavior of the `Style/SingleLineMethods` cop [changes](https://github.com/rubocop/rubocop/blob/v1.50.2/lib/rubocop/cop/style/single_line_methods.rb#L64-L65) to auto-correct single line methods to endless methods (because it knows it's targeting a version of ruby that supports endless methods)

So, not sure if that explains the issue for @andyw8 or @saturnflyer, but perhaps?

Bit of a side note but: when using Standard with Ruby 3, it actually _will_ convert single line methods to endless methods. The `Style/EndlessMethod` cop is disabled, but the auto-correction is handled by `Style/SingleLineMethods`, which is enabled. One thing that might make this test more bulletproof is if it were to explicitly pass in a `TargetRubyVersion` of 2.6 when asserting the Ruby 2 behavior (no endless methods), and then perhaps have another test that explicitly passes in the `TargetRubyVersion` of 3.2 and asserts that it does convert it to an endless method. Then it should behave the same whether or not the `.ruby-version` file is present.

**Comment by searls** [comment]
Interesting. Thanks for chasing that down, @maxjacobson. 

1. I think setting targetrubyversion explicitly to 2.6 to clear this test inconsistency would be great and we can consider this closed. Standard itself (apparently?) won't force single-line methods to endless methods
2. Separately, the logic itself seems kinda backwards (filed https://github.com/rubocop/rubocop/issues/11899 to ask)

Will fix this shortly.

**Comment by maxjacobson** [comment]
Good morning!!

> Thanks for chasing that down, @maxjacobson.

My pleasure! Had some time to kill before the Succession finale 😅 

> I think setting targetrubyversion explicitly to 2.6 to clear this test inconsistency would be great and we can consider this closed. 

Sweet, can confirm that fix resolves the test failure on my end, even when there's a local `.ruby-version` or a global `$HOME/.ruby-version` specifying 3.2.2. 🎉 

> Standard itself (apparently?) won't force single-line methods to endless methods

Right, as long as rubocop thinks it's targeting ruby 2. But if it thinks it's targeting ruby 3, it will.

After running `rbenv global 3.2.2`:

<img width="793" alt="Screenshot 2023-05-29 at 09 59 30" src="https://github.com/standardrb/standard/assets/1421211/f5fc77a3-6004-4e32-acc3-6c1fdec2c81a">

After running `rbenv global 2.7.6`:

<img width="826" alt="Screenshot 2023-05-29 at 10 01 36" src="https://github.com/standardrb/standard/assets/1421211/13050aca-a97f-414e-bda7-4e6a33fe02c2">

> Separately, the logic itself seems kinda backwards (filed https://github.com/rubocop/rubocop/issues/11899 to ask)

Nice! It's a good question, and I'll chime in here rather than butt in there... I want to interrogate this assumption:

> If someone has disabled Style/EndlessMethod, shouldn't endless method corrections by this cop be disallowed?

I think that argument can be made, but I think RuboCop's behavior makes sense when viewed from a certain lens:  When `Style/EndlessMethod` is disabled, that's a signal that the user does not want to take a position on endless methods. If the user wants to forbid endless methods, they would configure the cop like this:

```yaml
Style/EndlessMethod:
  Enabled: true
  EnforcedStyle: disallow
```

That config affirmatively signals "I care about endless methods, and I do not like them." 

Standard's configuration (

```yaml
Style/EndlessMethod:
  Enabled: false
```

) signals "I have not taken a position on endless methods, and so feel free to use them or don't, I don't care".

The behavior of the `Style/SingleLineMethods` cop is basically "unless you affirmatively said you don't like endless methods, well, I think they're cool, and I'm gonna give you one".

Is that reasonable? Probably? I think it's reasonable to assume that a user of ruby is open-minded about new syntax unless they affirmatively say otherwise.

**Comment by searls** [comment]
@maxjacobson yep, that makes more sense to me now -- feel free to chime in on that other thread with the same rationale, because I think you're probably exactly right about it

**Comment by andyw8** [comment]
Just confirming this solves it for me, thank you @maxjacobson!
