### ISSUE TITLE
Style/ArgumentsForwarding seems a bit heavy-handed

### ISSUE THREAD

**Issue by searls** [standardrb/standard#612]
Just updated standard to 1.34.0 and saw this failure:

```ruby
  def set_time_zone(&block)
    Time.use_zone(current_user.time_zone, &block)
  end
```

Which auto-fixes to this:

```ruby
  def set_time_zone(&)
    Time.use_zone(current_user.time_zone, &)
  end
```

I was kinda annoyed by this, and maybe even more annoyed when I realized that only `[blk, block, proc]` [trip the rule](https://docs.rubocop.org/rubocop/cops_style.html#styleargumentsforwarding).

Am I just being an old crank because I have 20 years of muscle memory writing `&blk`?

**Comment by bjeanes** [comment]
> Yeah, I have come to personally dislike being forced into this one, and I noticed as well that when I went back to maintain mocktail I had to add a bunch of #ignore directives.

Agreed

I just upgraded `standard` and the version of Rubocop that came with it (which is not the latest FWIW) rewrote some code from this rule and broke some code:

This original code:

```rb
    def method_missing(meth, *args, **opts, &blk)
      if delegated_class_method?(meth)
        opts[:account_id] = @account.id if @account
        opts[:env] = @env.merge(opts[:env] || {})
        opts[:session] = @session.merge(opts[:session] || {})
        @auth_class.send(meth, *args, **opts, &blk)
      elsif delegated_instance_method?(meth)
        internal { send(meth, *args, **opts, &blk) }
      else
        super
      end
    end
```

Was re-written into:

```rb
    def method_missing(meth, *, **opts, &)
      if delegated_class_method?(meth)
        opts[:account_id] = @account.id if @account
        opts[:env] = @env.merge(opts[:env] || {})
        opts[:session] = @session.merge(opts[:session] || {})
        @auth_class.send(meth, *, **opts, &)
      elsif delegated_instance_method?(meth)
        internal { send(meth, *args, **opts, &blk) }
      else
        super
      end
    end
```

This breaks, because there is still a reference to `*args` that gets unchanged.

I believe this is https://github.com/rubocop/rubocop/issues/12875, which _is_ fixed in newer versions. Leaving this here just as a breadcrumb to others in similar position.

I haven't been able to upgrade `rubocop` to a fixed version because the latest `standard` (understandably) has quite a tight version restriction. If I force a newer Rubocop, bundler actually _downgrades_ `standardrb` to 1.35.0:

![Screenshot 2024-11-11 at 10 33 35 am](https://github.com/user-attachments/assets/7fcbf757-8404-4dd6-be04-97cc52f89319)

For now, I'm going to avoid this `standard` upgrade until this rule is loosened as I agree that it is _faaar_ too heavy-handed and in many cases worsens readability (obv subjective, but that's my take!)

**Comment by searls** [comment]
Ok if @bjeanes is on board then I think I'd support a merge if someone sends a PR to disable it.

**Comment by bjeanes** [comment]
Is this just a case of flipping https://github.com/standardrb/standard/blob/e05a802600fcd97caa08a07c5c97701bce17a778/config/base.yml#L986-L987 ?
