### ISSUE TITLE
Line length?

### ISSUE THREAD

**Issue by pierry01** [standardrb/standard#648]
[Limit line length to 120 · Shopify/vscode-ruby-lsp@85740fa](https://github.com/Shopify/vscode-ruby-lsp/runs/15139758792?check_suite_focus=true)
https://github.com/Shopify/vscode-ruby-lsp/commit/85740fab7523dc42f6f19a309c0e2124a0aece16

I got your reasons, but it definitely should be configurable
![image](https://github.com/user-attachments/assets/6b3522a4-41aa-40de-a543-50eb92544f51)

There's a lot of articles on the internet mentioning that 120 characters is a good place to start
![image](https://github.com/user-attachments/assets/9ddad2fe-821b-4548-af1f-437c2c242894)

Between `freestyle vs 120 characters`, I guess 120 characters + configurable is the way!

**Comment by searls** [comment]
Rubocop's entire `Metric` department is intentionally disabled by Standard and for reasons that are so steeped in the basic principle of "never enable a rule that can't be adhered to in all reasonable cases". There are always going to be reasonable exceptional cases to long lines, so turning on any metric (line length, method length, etc) would just invite issues offering contradictory evidence (e.g. "See this code? I _need_ 148 chars!")

We're also never going to introduce configuration like this, because then Standard's formatting behavior would differ between projects, which would undermine the project's namesake.

If you want this kind of qualitative code quality stuff, I suggest looking at a tool designed specifically at measuring quality and that is equipped to do so on a deeper level, like [Reek](https://github.com/troessner/reek/blob/master/docs/Code-Smells.md) or its [family of friends](https://github.com/troessner/reek?tab=readme-ov-file#brothers-and-sisters)
